
# masses are in GeV/c^2

ID = {}
ID['1']   = {'catagory':'photon'  , 'symbol':'#gamma' ,                'mass':0.      }
ID['2']   = {'catagory':'electron', 'symbol':'e^{+}'  ,                'mass':.000511 }
ID['3']   = {'catagory':'electron', 'symbol':'e^{-}'  ,                'mass':.000511 }
ID['5']   = {'catagory':'muon',     'symbol':'#mu^{+}',                'mass':.105658 }
ID['6']   = {'catagory':'muon',     'symbol':'#mu^{-}',                'mass':.105658 }
ID['7']   = {'catagory':'oneutral', 'symbol':'#pi^{0}',                'mass':.134977 }
ID['8']   = {'catagory':'ocharged', 'symbol':'#pi^{+}',                'mass':.139570 }
ID['9']   = {'catagory':'ocharged', 'symbol':'#pi^{-}',                'mass':.139570 }
ID['10']  = {'catagory':'oneutral', 'symbol':'K_{L}^{0}',              'mass':.49761  }
ID['11']  = {'catagory':'ocharged', 'symbol':'K^{+}',                  'mass':.493677 }
ID['12']  = {'catagory':'ocharged', 'symbol':'K^{-}',                  'mass':.493677 }
ID['13']  = {'catagory':'neutron',  'symbol':'n',                      'mass':.939565 }
ID['14']  = {'catagory':'proton',   'symbol':'p',                      'mass':.938272 }
ID['15']  = {'catagory':'proton',   'symbol':'#bar{p}',                'mass':.938272 }
ID['16']  = {'catagory':'oneutral', 'symbol':'K_{S}^{0}',              'mass':.49761  }
ID['17']  = {'catagory':'oneutral', 'symbol':'#eta',                   'mass':.547862 }
ID['18']  = {'catagory':'oneutral', 'symbol':'#Lambda',                'mass':1.11568 }
ID['19']  = {'catagory':'ocharged', 'symbol':'#Sigma^{+}',             'mass':1.18937 }
ID['20']  = {'catagory':'oneutral', 'symbol':'#Sigma^{0}',             'mass':1.192642}
ID['21']  = {'catagory':'ocharged', 'symbol':'#Sigma^{-}',             'mass':1.97449 }
ID['22']  = {'catagory':'oneutral', 'symbol':'#Xi^{0}',                'mass':1.31486 }
ID['23']  = {'catagory':'ocharged', 'symbol':'#Xi^{-}',                'mass':1.32171 }
ID['24']  = {'catagory':'ocharged', 'symbol':'#Omega^{-}',             'mass':1.67245 }
ID['25']  = {'catagory':'neutron',  'symbol':'#bar{n}',                'mass':.939565 }
ID['26']  = {'catagory':'oneutral', 'symbol':'#bar{#Lambda}',          'mass':1.115683}
ID['27']  = {'catagory':'ocharged', 'symbol':'#bar{#Sigma}^{-}',       'mass':1.18937 }
ID['28']  = {'catagory':'oneutral', 'symbol':'#bar{#Sigma}^{0}',       'mass':1.192642}
ID['29']  = {'catagory':'ocharged', 'symbol':'#bar{#Sigma}^{+}',       'mass':1.197449}
ID['30']  = {'catagory':'oneutral', 'symbol':'#bar{#Xi}^{0}',          'mass':1.31486 }
ID['31']  = {'catagory':'ocharged', 'symbol':'#bar{#Xi}^{+}',          'mass':1.32171 }
ID['32']  = {'catagory':'ocharged', 'symbol':'#bar{#Omega}^{+}',       'mass':1.67245 }
ID['50']  = {'catagory':'oneutral', 'symbol':'#omega',                 'mass':.78265  }
ID['51']  = {'catagory':'oneutral', 'symbol':'#rho^{0}',               'mass':.769    }
ID['52']  = {'catagory':'ocharged', 'symbol':'#rho^{+}',               'mass':.7665   }
ID['53']  = {'catagory':'ocharged', 'symbol':'#rho^{-}',               'mass':.7665   }
ID['54']  = {'catagory':'ocharged', 'symbol':'#Delta^{++}',            'mass':1.2305  }
ID['55']  = {'catagory':'ocharged', 'symbol':'#Delta^{+}',             'mass':1.2318  }
ID['56']  = {'catagory':'oneutral', 'symbol':'#Delta^{0}',             'mass':1.2331  }
ID['57']  = {'catagory':'ocharged', 'symbol':'#Delta^{-}',             'mass':1.2344  }
ID['58']  = {'catagory':'ocharged', 'symbol':'#bar{#Delta}^{--}',      'mass':1.2309  }
ID['59']  = {'catagory':'ocharged', 'symbol':'#bar{#Delta}^{-}',       'mass':1.2323  }
ID['60']  = {'catagory':'oneutral', 'symbol':'#bar{#Delta}^{0}',       'mass':1.2336  }
ID['61']  = {'catagory':'ocharged', 'symbol':'#bar{#Delta}^{+}',       'mass':1.2349  }
ID['62']  = {'catagory':'oneutral', 'symbol':'K*^{0}',                 'mass':.89581  }
ID['63']  = {'catagory':'ocharged', 'symbol':'K*^{+}',                 'mass':.89166  }
ID['64']  = {'catagory':'ocharged', 'symbol':'#bar{K*}^{-}',           'mass':.89166  }
ID['65']  = {'catagory':'oneutral', 'symbol':'#bar{K*}^{0}',           'mass':.89581  }
ID['66']  = {'catagory':'oneutral', 'symbol':'#nu_{e}',                'mass':0.      }
ID['67']  = {'catagory':'oneutral', 'symbol':'#bar{#nu}_{e}',          'mass':0.      }
ID['68']  = {'catagory':'oneutral', 'symbol':'#nu_{#mu}',              'mass':0.      }
ID['69']  = {'catagory':'oneutral', 'symbol':'#bar{#nu}_{#mu}',        'mass':0.      }
ID['116'] = {'catagory':'oneutral', 'symbol':'D^{0}',                  'mass':1.8645  }
ID['117'] = {'catagory':'ocharged', 'symbol':'D^{+}',                  'mass':1.8697  }
ID['118'] = {'catagory':'ocharged', 'symbol':'#bar{D}^{-}',            'mass':1.8697  }
ID['119'] = {'catagory':'oneutral', 'symbol':'#bar{D}^{0}',            'mass':1.8645  }
ID['120'] = {'catagory':'ocharged', 'symbol':'D_{S}^{+}',              'mass':1.9682  }
ID['121'] = {'catagory':'ocharged', 'symbol':'#bar{D}_{S}^{-}',        'mass':1.9682  }
ID['122'] = {'catagory':'oneutral', 'symbol':'#eta_{C}',               'mass':2.9804  }
ID['123'] = {'catagory':'oneutral', 'symbol':'D*^{0}',                 'mass':2.0067  }
ID['124'] = {'catagory':'ocharged', 'symbol':'D*^{+}',                 'mass':2.0100  }
ID['125'] = {'catagory':'ocharged', 'symbol':'#bar{D*}^{-}',           'mass':2.0100  }
ID['126'] = {'catagory':'oneutral', 'symbol':'#bar{D*}^{0}',           'mass':2.0067  }
ID['127'] = {'catagory':'ocharged', 'symbol':'D*_{S}^{+}',             'mass':2.1121  }
ID['128'] = {'catagory':'ocharged', 'symbol':'#bar{D*_{S}}^{-}',       'mass':2.1121  }
ID['130'] = {'catagory':'oneutral', 'symbol':'J/#psi',                 'mass':3.096916}
ID['131'] = {'catagory':'ocharged', 'symbol':'#tau^{+}',               'mass':1.77699 }
ID['132'] = {'catagory':'ocharged', 'symbol':'#tau^{-}',               'mass':1.77699 }
ID['133'] = {'catagory':'oneutral', 'symbol':'#nu_{#tau}',             'mass':0.      }
ID['134'] = {'catagory':'oneutral', 'symbol':'#bar{#nu}_{#tau}',       'mass':0.      }
ID['137'] = {'catagory':'ocharged', 'symbol':'#Lambda^{+}_{C}',        'mass':2.28646 }
ID['138'] = {'catagory':'ocharged', 'symbol':'#Xi^{+}_{C}',            'mass':2.4679  }
ID['139'] = {'catagory':'oneutral', 'symbol':'#Xi^{0}_{C}',            'mass':2.4710  }
ID['140'] = {'catagory':'ocharged', 'symbol':'#Sigma^{++}_{C}',        'mass':2.45402 }
ID['141'] = {'catagory':'ocharged', 'symbol':'#Sigma^{+}_{C}',         'mass':2.4529  }
ID['142'] = {'catagory':'oneutral', 'symbol':'#Sigma^{0}_{C}',         'mass':2.45376 }
ID['143'] = {'catagory':'ocharged', 'symbol':"#Xi'^{+}_{C}",           'mass':2.5757  }
ID['144'] = {'catagory':'oneutral', 'symbol':"#Xi'^{0}_{C}",           'mass':2.5780  }
ID['145'] = {'catagory':'oneutral', 'symbol':'#Omega^{0}_{C}',         'mass':2.6975  }
ID['149'] = {'catagory':'ocharged', 'symbol':'#bar{#Lambda_{C}}^{-}',  'mass':2.28646 }
ID['150'] = {'catagory':'ocharged', 'symbol':'#bar{#Xi_{C}}^{-}',      'mass':2.4679  }
ID['151'] = {'catagory':'oneutral', 'symbol':'#bar{#Xi_{C}}^{0}',      'mass':2.4710  }
ID['152'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma_{C}}^{--}',  'mass':2.45402 }
ID['153'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma_{C}}^{-}',   'mass':2.4529  }
ID['154'] = {'catagory':'oneutral', 'symbol':'#bar{#Sigma_{C}}^{0}',   'mass':2.4576  }
ID['155'] = {'catagory':'ocharged', 'symbol':"#bar{#Xi'_{C}}^{-}",     'mass':2.5757  }
ID['156'] = {'catagory':'oneutral', 'symbol':"#bar{#Xi'_{C}}^{0}",     'mass':2.5780  }
ID['157'] = {'catagory':'oneutral', 'symbol':'#bar{#Omega_{C}}^{0}',   'mass':2.6975  }
ID['161'] = {'catagory':'ocharged', 'symbol':'#Sigma*_{C}^{++}',       'mass':2.5184  }
ID['162'] = {'catagory':'ocharged', 'symbol':'#Sigma*_{C}^{+}',        'mass':2.5175  }
ID['163'] = {'catagory':'oneutral', 'symbol':'#Sigma*_{C}^{0}',        'mass':2.5180  }
ID['171'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma*_{C}}^{--}', 'mass':2.5184  }
ID['172'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma*_{C}}^{-}',  'mass':2.5175  }
ID['173'] = {'catagory':'oneutral', 'symbol':'#bar{#Sigma*_{C}}^{0}',  'mass':2.5180  }
ID['176'] = {'catagory':'oneutral', 'symbol':'B^{0}',                  'mass':5.27961 }
ID['177'] = {'catagory':'ocharged', 'symbol':'B^{+}',                  'mass':5.27929 }
ID['178'] = {'catagory':'ocharged', 'symbol':'#bar{B}^{-}',            'mass':5.27929 }
ID['179'] = {'catagory':'oneutral', 'symbol':'#bar{B}^{0}',            'mass':5.27961 }
ID['180'] = {'catagory':'oneutral', 'symbol':'B_{S}^{0}',              'mass':5.36679 }
ID['181'] = {'catagory':'oneutral', 'symbol':'#bar{B_{S}}^{0}',        'mass':5.36679 }
ID['182'] = {'catagory':'ocharged', 'symbol':'B_{C}^{+}',              'mass':6.2751  }
ID['183'] = {'catagory':'ocharged', 'symbol':'#bar{B_{C}}^{-}',        'mass':6.2751  }
ID['184'] = {'catagory':'oneutral', 'symbol':'#Lambda_{b}^{0}',        'mass':5.61951 }
ID['185'] = {'catagory':'ocharged', 'symbol':'#Sigma_{b}^{-}',         'mass':5.8155  }
ID['186'] = {'catagory':'ocharged', 'symbol':'#Sigma_{b}^{+}',         'mass':5.8113  }
ID['187'] = {'catagory':'oneutral', 'symbol':'#Xi_{b}^{0}',            'mass':5.7918  }
ID['188'] = {'catagory':'ocharged', 'symbol':'#Xi_{b}^{-}',            'mass':5.7944  }
ID['189'] = {'catagory':'ocharged', 'symbol':'#Omega_{b}^{-}',         'mass':6.0480  }
ID['190'] = {'catagory':'oneutral', 'symbol':'#bar{#Lambda_{b}}^{0}',  'mass':5.61951 }
ID['191'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma_{b}}^{+}',   'mass':5.8155  }
ID['192'] = {'catagory':'ocharged', 'symbol':'#bar{#Sigma_{b}}^{-}',   'mass':5.8113  }
ID['193'] = {'catagory':'oneutral', 'symbol':'#bar{#Xi_{b}}^{0}',      'mass':5.7918  }
ID['194'] = {'catagory':'ocharged', 'symbol':'#bar{#Xi_{b}}^{+}',      'mass':5.7944  }
ID['195'] = {'catagory':'ocharged', 'symbol':'#bar{#Omega_{b}}^{+}',   'mass':6.0480  }


